name: PearlTP
main: com.kdude63.pearltp.main
version: 1.0 (Build 25)
description: Allows everyone to teleport at the cost of a configurable amount of enderpearls.
author: kdude63
dev-url: http://dev.bukkit.org/server-mods/pearltp/
commands:
    ptp:
       description: Teleports yourself to another player or coordinates.
       usage: "Usage: /ptp <target> or <x> <y> <z>"
       permission: pearltp.teleport